name: quit # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: "2.0+git" # just for humans, typically '1.2+git' or '1.3.2'
contact: javierribal@gmail.com
issues: https://github.com/JavierRibaldelRio/Quit/issues
source-code: https://github.com/JavierRibaldelRio/Quit.git
website: https://javierribaldelrio.github.io/Quit/
summary: Linux shutdown manager # 79 char long summary
description: |
  Quit is an application for Linux terminal to shutdown, reboot or suspend the computer. It is developed in C++. You can also set a timed shutdown. To use it, you will need the "sudo" command and the gcc compiler. Both are usually pre-installed in the system.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  quit:
    plugin: autotools
    source: https://javierribaldelrio.github.io/Quit/quit-2.0.tar.gz
    source-type: tar
    build-packages:
      - g++
      - make

apps:
  quit:
    command: quit
